version: '3'
networks:
  habiters-network:
    driver: bridge

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email xogmlwkdi77@gmail.com --agree-tos --no-eff-email --force-renewal -d api.habiters.store
    networks:
      - habiters-network
  nginx:
    container_name: habiters-nginx
    image: nginx
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - habiters-network

  web:
    container_name: habiters-app
    image: hantaehee/habiters
    depends_on:
      - db
    expose:
      - 8080
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_URI: ${KAKAO_URI}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_URI: ${GOOGLE_URI}
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      NAVER_URI: ${NAVER_URI}
      NCP_API_ACCESS_KEY: ${NCP_API_ACCESS_KEY}
      NCP_SECRET_KEY: ${NCP_SECRET_KEY}
    networks:
      - habiters-network

  db:
    container_name: habiters-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: habiters-db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    networks:
      - habiters-network


