version: '3'
networks:
  habiters-network:
    driver: bridge

services:
  nginx:
    container_name: habiters-nginx
    image: nginx
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - habiters-network

  web:
    container_name: habiters-app
    image: hantaehee/habiters
    depends_on:
      - db
    expose:
      - 8080
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_URI: ${KAKAO_URI}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_URI: ${GOOGLE_URI}
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      NAVER_URI: ${NAVER_URI}
    networks:
      - habiters-network

  db:
    container_name: habiters-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: habiters-db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    networks:
      - habiters-network


