drop table if exists diary cascade;
drop table if exists habbit cascade;
drop table if exists habit_check cascade;
drop table if exists member cascade;
create table diary
(
    id              bigint generated by default as identity,
    created_date    timestamp(6),
    deleted         boolean not null,
    updated_date    timestamp(6),
    content         varchar(255),
    end_update_date timestamp(6),
    member_id       bigint,
    primary key (id)
);
create table habbit
(
    id           bigint generated by default as identity,
    created_date timestamp(6),
    deleted      boolean not null,
    updated_date timestamp(6),
    content      varchar(255),
    member_id    bigint,
    primary key (id)
);
create table habit_check
(
    id           bigint generated by default as identity,
    created_date timestamp(6),
    deleted      boolean not null,
    updated_date timestamp(6),
    checked      boolean not null,
    habit_id     bigint,
    primary key (id)
);
create table member
(
    id              bigint generated by default as identity,
    created_date    timestamp(6),
    deleted         boolean not null,
    updated_date    timestamp(6),
    email           varchar(255),
    nick_name       varchar(255),
    oauth_id        varchar(255),
    profile_img_url varchar(255),
    provider        varchar(255),
    primary key (id)
);
alter table if exists diary add constraint FKbyluyva0mxnf5jitf297oxlxd foreign key (member_id) references member;
alter table if exists habbit add constraint FK2tlodega5v0fas0uv1ksxu8ci foreign key (member_id) references member;
alter table if exists habit_check add constraint FK6exrsx5hm05v3ur6c3ttiqopd foreign key (habit_id) references habbit

